# Generated by Django 4.1.4 on 2023-01-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_bath_rooms_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Apartama', 'Apartama'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], default='Condo', max_length=10),
        ),
    ]
