# Generated by Django 4.1.4 on 2022-12-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
