# Generated by Django 4.1.4 on 2022-12-29 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_1',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='image_2',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='image_3',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='image_4',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='image_5',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
