# Generated by Django 4.1.4 on 2022-12-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_image_1_alter_house_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='avgRating',
            field=models.IntegerField(default=1),
        ),
    ]
