# Generated by Django 4.1.4 on 2023-01-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_house_oldprice_alter_house_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
