# Generated by Django 4.1.4 on 2023-01-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_image_3_remove_listing_image_4_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='house',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(default=10000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.IntegerField(default=10000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='order.order'),
        ),
    ]
